USE MyDB; -- Use MyDB as a current database

PRINT 'SELECT 1 - Show the tables exist'
SELECT
SUBSTRING(TABLE_CATALOG, 1, 20) [Database],
SUBSTRING(TABLE_NAME, 1, 20)[Table]
FROM INFORMATION_SCHEMA.TABLES;

PRINT 'SELECT 2 - Show that the tables have the correct columns'
SELECT
SUBSTRING(TABLE_NAME, 1, 20)[Table],
SUBSTRING(COLUMN_NAME, 1, 20) [Column],
ORDINAL_POSITION[Pos],
SUBSTRING(DATA_TYPE, 1, 20) [Type],
CHARACTER_MAXIMUM_LENGTH[Length]
FROM INFORMATION_SCHEMA.COLUMNS;

PRINT 'SELECT 3 - Show that all the constraints (PK, CK and FK) were set up properly'
SELECT
SUBSTRING(TC.TABLE_NAME, 1, 15)[Table],
SUBSTRING(CCU.COLUMN_NAME, 1, 20)[Column],
SUBSTRING(TC.CONSTRAINT_NAME, 1, 35) [Constraint],
SUBSTRING(TC.CONSTRAINT_TYPE, 1, 11) [Type],
COALESCE(
SUBSTRING(CC.CHECK_CLAUSE, 1, 75),
SUBSTRING(KCU.TABLE_NAME, 1 , 15) + '(' +
SUBSTRING(KCU.COLUMN_NAME, 1, 20) + ')',
'Missing'
) [Constraint Details]
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
ON TC.CONSTRAINT_NAME = CCU.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS CC
ON TC.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
ORDER BY [Table], [Constraint] DESC;
