// <auto-generated />
using DatabaseExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace DatabaseExplorer.Migrations.ColorPicker;

[DbContext(typeof(ColorContext))]
partial class ColorContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

        modelBuilder.Entity("ColorPicker.Models.Color", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("GroupId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("GroupId");

                b.ToTable("Color");
            });

        modelBuilder.Entity("ColorPicker.Models.Group", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Group");
            });

        modelBuilder.Entity("ColorPicker.Models.Color", b =>
            {
                b.HasOne("ColorPicker.Models.Group", "Group")
                    .WithMany("Colors")
                    .HasForeignKey("GroupId")
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .IsRequired();

                b.Navigation("Group");
            });

        modelBuilder.Entity("ColorPicker.Models.Group", b =>
            {
                b.Navigation("Colors");
            });
#pragma warning restore 612, 618
    }
}
