// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTrackerBlazor.Server.Data;

#nullable disable

namespace MovieTrackerBlazor.Server.Migrations;

[DbContext(typeof(MovieTrackerContext))]
partial class MovieTrackerContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("MovieTrackerBlazor.Shared.Genre", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("GenreDescriptios")
                    .HasMaxLength(25)
                    .HasColumnType("nvarchar(25)");

                b.HasKey("Id");

                b.ToTable("Genre");
            });

        modelBuilder.Entity("MovieTrackerBlazor.Shared.Movie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("DateSeen")
                    .HasColumnType("datetime2");

                b.Property<int?>("GenreId")
                    .HasColumnType("int");

                b.Property<int?>("Rating")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.HasIndex("GenreId");

                b.ToTable("Movie");
            });

        modelBuilder.Entity("MovieTrackerBlazor.Shared.Movie", b =>
            {
                b.HasOne("MovieTrackerBlazor.Shared.Genre", "Genre")
                    .WithMany()
                    .HasForeignKey("GenreId");

                b.Navigation("Genre");
            });
#pragma warning restore 612, 618
    }
}
